ARG VARIANT="trixie"
FROM buildpack-deps:${VARIANT}-curl@sha256:afc155d4924f7a6a520c49762d465bf39247e40eb6bcd2686c4354228cf90cf1
LABEL org.opencontainers.image.source="https://github.com/docker-library/buildpack-deps"
LABEL maintainer="Kenichi NAKASAKA TKS Team <k-nakasaka@tg-inet.co.jp>"
LABEL maintainer="Megumi OGATA TKS Team <me-ogata@tg-inet.co.jp>"
