ARG VARIANT="cuda11.8-cudnn9"
FROM pytorch/pytorch:2.7.1-${VARIANT}-devel
LABEL org.opencontainers.image.source="https://hub.docker.com/layers/pytorch/pytorch/"
LABEL maintainer="Kenichi NAKASAKA TKS Team <k-nakasaka@tg-inet.co.jp>"
